// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fqagfgjwpskhoicqlnhv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxYWdmZ2p3cHNraG9pY3Fsbmh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5ODYyNDEsImV4cCI6MjA2NzU2MjI0MX0.8Sq5KPjDEthMCkySPZC71Z3cAZLMFQd_VMnZvndpqfw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});